language:
    node_js
node_js:
    - 0.12

before_script:
    - git config --global user.email "danmitchellster@gmail.com"
    - git config --global user.name "damitchell"
    - npm install -g bower
    - bower install

script:
    - gulp deploy
